### ISSUE TITLE
Filters not visible in Django Admin when dark mode is turned on

### ISSUE THREAD

**Issue by uche-wealth** [alonw0/django-charfield-filters#1]
In Django Admin, when using light mode, everything works well and filters are clearly seen but when it's toggled to dark mode, the filter values are hardly visible. It is most likely a styling issue and I was wondering if it could be resolved ASAP as my app in production uses `django-charfield-filters` and some users prefer dark mode. 

This has been tested on Windows, Mac, Android and iOS devices and it's basically the same. Please look at the attached screenshots.

Works well with light mode: 

![Image](https://github.com/user-attachments/assets/7f06eb28-83b3-4216-9883-944dc5f8b5c9) 

but values are invisible in dark mode :

![Image](https://github.com/user-attachments/assets/3a205b14-6fd8-463f-858d-21328442f7c1)

Kindly assist in resolving this. Thank you for helping out.

**Comment by alonw0** [comment]
Fixed in v0.1.2
----
If you liked the project - please consider adding a star 🙏

**Comment by uche-wealth** [comment]
Thanks for helping out, I've given a star.... However the experience is still the same. I ran `pip install -U django-charfield-filters` to upgrade to 0.1.2 and the values are still not visible in dark mode.

**Comment by alonw0** [comment]
Please try v0.1.3 and also hard refresh for css updates.

**Comment by uche-wealth** [comment]
PERFECT! Thank you. Works super now!
